version: '3'
services:
  coop:
    build: openresty
    ports:
      - 80:80
    networks:
      - redis-net
    depends_on:
      - database

  database:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-net
    hostname: database
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data: